'use client'

import { Loader2 } from 'lucide-react'
import { theme } from '@/lib/theme'
import { useEditorStore } from '@/lib/store/useEditorStore'
import { useWakeLock } from '@/app/editor/hooks/useWakeLock'
import BuilderLimitToast from './BuilderLimitToast'
import BuildViewer from './BuildViewer'

export default function BuilderMain() {
    // Building with physical dice takes a while - don't let the screen sleep
    useWakeLock()

    const diceGrid = useEditorStore(state => state.diceGrid)

    // The grid is regenerated by the dice pipeline after a restore - show a
    // spinner until it lands. BuildViewer takes a non-null grid so its hooks
    // never have to guard.
    if (!diceGrid) {
        return (
            <div className="w-full h-full flex flex-col items-center justify-center gap-3">
                <Loader2 className="w-8 h-8 animate-spin" style={{ color: theme.colors.accent.pink }} />
                <span className="text-sm" style={{ color: theme.colors.text.secondary }}>Preparing your build...</span>
            </div>
        )
    }

    return (
        <div className="relative w-full h-full">
            <BuilderLimitToast />
            <BuildViewer grid={diceGrid} />
        </div>
    )
}
